package com.bera.josaahelpertool.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF028BE4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D35)
val md_theme_light_secondary = Color(0xFF535F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E4F7)
val md_theme_light_onSecondaryContainer = Color(0xFF0F1C2B)
val md_theme_light_tertiary = Color(0xFF3A5BA9)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001848)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF9DCAFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0062A1)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)

//val md_theme_dark_primary = Color(0xFF9DCAFF)
//val md_theme_dark_onPrimary = Color(0xFF003257)
//val md_theme_dark_primaryContainer = Color(0xFF00497B)
//val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
//val md_theme_dark_secondary = Color(0xFFBAC8DB)
//val md_theme_dark_onSecondary = Color(0xFF253140)
//val md_theme_dark_secondaryContainer = Color(0xFF3B4858)
//val md_theme_dark_onSecondaryContainer = Color(0xFFD6E4F7)
//val md_theme_dark_tertiary = Color(0xFFB2C5FF)
//val md_theme_dark_onTertiary = Color(0xFF002B73)
//val md_theme_dark_tertiaryContainer = Color(0xFF1E438F)
//val md_theme_dark_onTertiaryContainer = Color(0xFFDAE2FF)
//val md_theme_dark_error = Color(0xFFFFB4AB)
//val md_theme_dark_errorContainer = Color(0xFF93000A)
//val md_theme_dark_onError = Color(0xFF690005)
//val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
//val md_theme_dark_background = Color(0xFF1A1C1E)
//val md_theme_dark_onBackground = Color(0xFFE2E2E6)
//val md_theme_dark_surface = Color(0xFF1A1C1E)
//val md_theme_dark_onSurface = Color(0xFFE2E2E6)
//val md_theme_dark_surfaceVariant = Color(0xFF42474E)
//val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
//val md_theme_dark_outline = Color(0xFF8C9199)
//val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
//val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
//val md_theme_dark_inversePrimary = Color(0xFF0062A1)
//val md_theme_dark_shadow = Color(0xFF000000)
//val md_theme_dark_surfaceTint = Color(0xFF9DCAFF)
//val md_theme_dark_outlineVariant = Color(0xFF42474E)
//val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF109CFC)